<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240502130623 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE wp_bmscommentmeta');
        $this->addSql('DROP TABLE wp_bmscomments');
        $this->addSql('DROP TABLE wp_bmslinks');
        $this->addSql('DROP TABLE wp_bmsoptions');
        $this->addSql('DROP TABLE wp_bmspostmeta');
        $this->addSql('DROP TABLE wp_bmsposts');
        $this->addSql('DROP TABLE wp_bmstermmeta');
        $this->addSql('DROP TABLE wp_bmsterms');
        $this->addSql('DROP TABLE wp_bmsterm_relationships');
        $this->addSql('DROP TABLE wp_bmsterm_taxonomy');
        $this->addSql('DROP TABLE wp_bmsusermeta');
        $this->addSql('DROP TABLE wp_bmsusers');
        $this->addSql('DROP TABLE wp_bmszbs_admlog');
        $this->addSql('DROP TABLE wp_bmszbs_aka');
        $this->addSql('DROP TABLE wp_bmszbs_companies');
        $this->addSql('DROP TABLE wp_bmszbs_contacts');
        $this->addSql('DROP TABLE wp_bmszbs_customfields');
        $this->addSql('DROP TABLE wp_bmszbs_dbmigration_meta');
        $this->addSql('DROP TABLE wp_bmszbs_dbmigration_posts');
        $this->addSql('DROP TABLE wp_bmszbs_events');
        $this->addSql('DROP TABLE wp_bmszbs_event_reminders');
        $this->addSql('DROP TABLE wp_bmszbs_externalsources');
        $this->addSql('DROP TABLE wp_bmszbs_forms');
        $this->addSql('DROP TABLE wp_bmszbs_invoices');
        $this->addSql('DROP TABLE wp_bmszbs_lineitems');
        $this->addSql('DROP TABLE wp_bmszbs_logs');
        $this->addSql('DROP TABLE wp_bmszbs_meta');
        $this->addSql('DROP TABLE wp_bmszbs_notifications');
        $this->addSql('DROP TABLE wp_bmszbs_object_links');
        $this->addSql('DROP TABLE wp_bmszbs_quotes');
        $this->addSql('DROP TABLE wp_bmszbs_quotes_templates');
        $this->addSql('DROP TABLE wp_bmszbs_security_log');
        $this->addSql('DROP TABLE wp_bmszbs_segments');
        $this->addSql('DROP TABLE wp_bmszbs_segments_conditions');
        $this->addSql('DROP TABLE wp_bmszbs_settings');
        $this->addSql('DROP TABLE wp_bmszbs_sys_cronmanagerlogs');
        $this->addSql('DROP TABLE wp_bmszbs_sys_email');
        $this->addSql('DROP TABLE wp_bmszbs_sys_email_hist');
        $this->addSql('DROP TABLE wp_bmszbs_tags');
        $this->addSql('DROP TABLE wp_bmszbs_tags_links');
        $this->addSql('DROP TABLE wp_bmszbs_tax_table');
        $this->addSql('DROP TABLE wp_bmszbs_temphash');
        $this->addSql('DROP TABLE wp_bmszbs_tracking');
        $this->addSql('DROP TABLE wp_bmszbs_transactions');
        $this->addSql('DROP TABLE wp_bmszbs_workflows');
        $this->addSql('ALTER TABLE user ADD status VARCHAR(255) DEFAULT NULL, CHANGE roles roles JSON NOT NULL COMMENT \'(DC2Type:json)\', CHANGE interesrt_course interesrt_course JSON DEFAULT NULL COMMENT \'(DC2Type:json)\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE wp_bmscommentmeta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, comment_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX comment_id (comment_id), INDEX meta_key (meta_key(191)), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmscomments (comment_ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, comment_post_ID BIGINT UNSIGNED DEFAULT 0 NOT NULL, comment_author TINYTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_author_email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_author_url VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_author_IP VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_date DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, comment_date_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, comment_content TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_karma INT DEFAULT 0 NOT NULL, comment_approved VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'1\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_agent VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_type VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'comment\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_parent BIGINT UNSIGNED DEFAULT 0 NOT NULL, user_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, INDEX comment_date_gmt (comment_date_gmt), INDEX comment_post_ID (comment_post_ID), INDEX comment_parent (comment_parent), INDEX comment_approved_date_gmt (comment_approved, comment_date_gmt), INDEX comment_author_email (comment_author_email(10)), PRIMARY KEY(comment_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmslinks (link_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, link_url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_target VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_visible VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'Y\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_owner BIGINT UNSIGNED DEFAULT 1 NOT NULL, link_rating INT DEFAULT 0 NOT NULL, link_updated DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, link_rel VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_notes MEDIUMTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_rss VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX link_visible (link_visible), PRIMARY KEY(link_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmsoptions (option_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, option_name VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, option_value LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, autoload VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'yes\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX autoload (autoload), UNIQUE INDEX option_name (option_name), PRIMARY KEY(option_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmspostmeta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, post_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX meta_key (meta_key(191)), INDEX post_id (post_id), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmsposts (ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, post_author BIGINT UNSIGNED DEFAULT 0 NOT NULL, post_date DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_date_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_content LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_title TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_excerpt TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_status VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'publish\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_status VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'open\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, ping_status VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'open\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_password VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_name VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, to_ping TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, pinged TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_modified DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_modified_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_content_filtered LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_parent BIGINT UNSIGNED DEFAULT 0 NOT NULL, guid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, menu_order INT DEFAULT 0 NOT NULL, post_type VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'post\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_mime_type VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_count BIGINT DEFAULT 0 NOT NULL, INDEX type_status_date (post_type, post_status, post_date, ID), INDEX post_parent (post_parent), INDEX post_author (post_author), INDEX post_name (post_name(191)), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmstermmeta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, term_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX term_id (term_id), INDEX meta_key (meta_key(191)), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmsterms (term_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, slug VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, term_group BIGINT DEFAULT 0 NOT NULL, INDEX slug (slug(191)), INDEX name (name(191)), PRIMARY KEY(term_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmsterm_relationships (object_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, term_taxonomy_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, term_order INT DEFAULT 0 NOT NULL, INDEX term_taxonomy_id (term_taxonomy_id), PRIMARY KEY(object_id, term_taxonomy_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmsterm_taxonomy (term_taxonomy_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, term_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, taxonomy VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, description LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, parent BIGINT UNSIGNED DEFAULT 0 NOT NULL, count BIGINT DEFAULT 0 NOT NULL, UNIQUE INDEX term_id_taxonomy (term_id, taxonomy), INDEX taxonomy (taxonomy), PRIMARY KEY(term_taxonomy_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmsusermeta (umeta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX user_id (user_id), INDEX meta_key (meta_key(191)), PRIMARY KEY(umeta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmsusers (ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_login VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_pass VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_nicename VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_url VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_registered DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, user_activation_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_status INT DEFAULT 0 NOT NULL, display_name VARCHAR(250) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX user_login_key (user_login), INDEX user_nicename (user_nicename), INDEX user_email (user_email), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_admlog (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsadmlog_status INT NOT NULL, zbsadmlog_cat VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsadmlog_str VARCHAR(500) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsadmlog_time INT DEFAULT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_aka (ID INT AUTO_INCREMENT NOT NULL, aka_type INT DEFAULT NULL, aka_id INT NOT NULL, aka_alias VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, aka_created INT DEFAULT NULL, aka_lastupdated INT DEFAULT NULL, INDEX aka_id (aka_id, aka_alias), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_companies (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsco_status VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_name VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_email VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_addr1 VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_addr2 VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_city VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_county VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_country VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_postcode VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_secaddr1 VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_secaddr2 VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_seccity VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_seccounty VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_seccountry VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_secpostcode VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_maintel VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_sectel VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_wpid INT DEFAULT NULL, zbsco_avatar VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_tw VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_li VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_fb VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsco_created INT NOT NULL, zbsco_lastupdated INT NOT NULL, zbsco_lastcontacted INT DEFAULT NULL, INDEX name (zbsco_name), INDEX email (zbsco_email), INDEX created (zbsco_created), INDEX wpid (zbsco_wpid), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_contacts (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsc_status VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_email VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_prefix VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_fname VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_lname VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_addr1 VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_addr2 VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_city VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_county VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_country VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_postcode VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_secaddr1 VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_secaddr2 VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_seccity VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_seccounty VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_seccountry VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_secpostcode VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_hometel VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_worktel VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_mobtel VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_wpid INT DEFAULT NULL, zbsc_avatar VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_tw VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_li VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_fb VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_created INT NOT NULL, zbsc_lastupdated INT NOT NULL, zbsc_lastcontacted INT DEFAULT NULL, INDEX zbsc_status (zbsc_status), INDEX zbsc_email (zbsc_email, zbsc_wpid), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_customfields (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbscf_objtype INT NOT NULL, zbscf_objid INT NOT NULL, zbscf_objkey VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbscf_objval VARCHAR(2000) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbscf_created INT NOT NULL, zbscf_lastupdated INT NOT NULL, FULLTEXT INDEX search (zbscf_objval), INDEX TYPEIDKEY (zbscf_objtype, zbscf_objid, zbscf_objkey), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_dbmigration_meta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, wpID BIGINT UNSIGNED NOT NULL, zbsID BIGINT UNSIGNED NOT NULL, post_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, meta_value LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, INDEX post_id (post_id), INDEX meta_key (meta_key), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_dbmigration_posts (ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, wpID BIGINT UNSIGNED NOT NULL, zbsID BIGINT UNSIGNED NOT NULL, post_author BIGINT UNSIGNED DEFAULT 0 NOT NULL, post_date DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_date_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_content LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, post_title TEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, post_excerpt TEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, post_status VARCHAR(20) CHARACTER SET utf8 DEFAULT \'publish\' NOT NULL COLLATE `utf8_general_ci`, comment_status VARCHAR(20) CHARACTER SET utf8 DEFAULT \'open\' NOT NULL COLLATE `utf8_general_ci`, ping_status VARCHAR(20) CHARACTER SET utf8 DEFAULT \'open\' NOT NULL COLLATE `utf8_general_ci`, post_password VARCHAR(255) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_general_ci`, post_name VARCHAR(200) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_general_ci`, to_ping TEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, pinged TEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, post_modified DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_modified_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_content_filtered LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, post_parent BIGINT UNSIGNED DEFAULT 0 NOT NULL, guid VARCHAR(255) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_general_ci`, menu_order INT DEFAULT 0 NOT NULL, post_type VARCHAR(20) CHARACTER SET utf8 DEFAULT \'post\' NOT NULL COLLATE `utf8_general_ci`, post_mime_type VARCHAR(100) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_general_ci`, comment_count BIGINT DEFAULT 0 NOT NULL, INDEX post_author (post_author), INDEX post_name (post_name), INDEX type_status_date (post_type, post_status, post_date, ID), INDEX post_parent (post_parent), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_events (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbse_title VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbse_desc LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbse_start INT NOT NULL, zbse_end INT NOT NULL, zbse_complete TINYINT(1) DEFAULT -1 NOT NULL, zbse_show_on_portal TINYINT(1) DEFAULT -1 NOT NULL, zbse_show_on_cal TINYINT(1) DEFAULT -1 NOT NULL, zbse_created INT NOT NULL, zbse_lastupdated INT DEFAULT NULL, INDEX endint (zbse_end), INDEX created (zbse_created), INDEX title (zbse_title), INDEX startint (zbse_start), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_event_reminders (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbser_event INT NOT NULL, zbser_remind_at INT DEFAULT -1 NOT NULL, zbser_sent TINYINT(1) DEFAULT -1 NOT NULL, zbser_created INT NOT NULL, zbser_lastupdated INT DEFAULT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_externalsources (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbss_objtype INT DEFAULT -1 NOT NULL, zbss_objid INT NOT NULL, zbss_source VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbss_uid VARCHAR(300) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbss_origin VARCHAR(400) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbss_created INT NOT NULL, zbss_lastupdated INT NOT NULL, INDEX zbss_uid+zbss_source+zbss_objtype (zbss_uid, zbss_source, zbss_objtype), INDEX zbss_objid (zbss_objid), INDEX zbss_origin (zbss_origin), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_forms (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsf_title VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_style VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsf_views INT DEFAULT 0, zbsf_conversions INT DEFAULT 0, zbsf_label_header VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_label_subheader VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_label_firstname VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_label_lastname VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_label_email VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_label_message VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_label_button VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_label_successmsg VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_label_spammsg VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_include_terms_check TINYINT(1) DEFAULT -1 NOT NULL, zbsf_terms_url VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_redir_url VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_font VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_colour_bg VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_colour_font VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_colour_emphasis VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsf_created INT NOT NULL, zbsf_lastupdated INT NOT NULL, INDEX title (zbsf_title), INDEX created (zbsf_created), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_invoices (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsi_id_override VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_parent INT DEFAULT NULL, zbsi_status VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsi_hash VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_send_attachments TINYINT(1) DEFAULT -1 NOT NULL, zbsi_pdf_template VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_portal_template VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_email_template VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_invoice_frequency INT DEFAULT -1, zbsi_currency VARCHAR(4) CHARACTER SET utf8 DEFAULT \'-1\' NOT NULL COLLATE `utf8_general_ci`, zbsi_pay_via INT DEFAULT NULL, zbsi_logo_url VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_address_to_objtype INT DEFAULT -1 NOT NULL, zbsi_addressed_from VARCHAR(600) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_addressed_to VARCHAR(600) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_allow_partial TINYINT(1) DEFAULT -1 NOT NULL, zbsi_allow_tip TINYINT(1) DEFAULT -1 NOT NULL, zbsi_hours_or_quantity TINYINT(1) DEFAULT 1 NOT NULL, zbsi_date INT NOT NULL, zbsi_due_date INT DEFAULT NULL, zbsi_paid_date INT DEFAULT -1, zbsi_hash_viewed INT DEFAULT -1, zbsi_hash_viewed_count INT DEFAULT 0, zbsi_portal_viewed INT DEFAULT -1, zbsi_portal_viewed_count INT DEFAULT 0, zbsi_net NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbsi_discount NUMERIC(18, 2) DEFAULT \'0.00\', zbsi_discount_type VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_shipping NUMERIC(18, 2) DEFAULT \'0.00\', zbsi_shipping_taxes VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_shipping_tax NUMERIC(18, 2) DEFAULT \'0.00\', zbsi_taxes VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsi_tax NUMERIC(18, 2) DEFAULT \'0.00\', zbsi_total NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbsi_created INT NOT NULL, zbsi_lastupdated INT NOT NULL, INDEX hash (zbsi_hash), INDEX idoverride (zbsi_id_override), INDEX created (zbsi_created), INDEX parent (zbsi_parent), INDEX status (zbsi_status), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_lineitems (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsli_order INT DEFAULT NULL, zbsli_title VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsli_desc VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsli_quantity NUMERIC(18, 2) DEFAULT NULL, zbsli_price NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbsli_currency VARCHAR(4) CHARACTER SET utf8 DEFAULT \'-1\' NOT NULL COLLATE `utf8_general_ci`, zbsli_net NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbsli_discount NUMERIC(18, 2) DEFAULT \'0.00\', zbsli_fee NUMERIC(18, 2) DEFAULT \'0.00\', zbsli_shipping NUMERIC(18, 2) DEFAULT \'0.00\', zbsli_shipping_taxes VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsli_shipping_tax NUMERIC(18, 2) DEFAULT \'0.00\', zbsli_taxes VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsli_tax NUMERIC(18, 2) DEFAULT \'0.00\', zbsli_total NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbsli_created INT NOT NULL, zbsli_lastupdated INT NOT NULL, INDEX `order` (zbsli_order), INDEX created (zbsli_created), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_logs (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsl_objtype INT NOT NULL, zbsl_objid INT NOT NULL, zbsl_type VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsl_shortdesc VARCHAR(300) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsl_longdesc LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsl_pinned INT DEFAULT NULL, zbsl_created INT NOT NULL, zbsl_lastupdated INT NOT NULL, INDEX zbsl_objid (zbsl_objid), INDEX zbsl_created (zbsl_created), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_meta (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsm_objtype INT NOT NULL, zbsm_objid INT NOT NULL, zbsm_key VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsm_val LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsm_created INT NOT NULL, zbsm_lastupdated INT NOT NULL, INDEX zbsm_objid+zbsm_key+zbsm_objtype (zbsm_objid, zbsm_key, zbsm_objtype), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_notifications (id INT UNSIGNED AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsnotify_recipient_id INT NOT NULL, zbsnotify_sender_id INT NOT NULL, zbsnotify_unread TINYINT(1) DEFAULT 1 NOT NULL, zbsnotify_emailed TINYINT(1) DEFAULT 0 NOT NULL, zbsnotify_type VARCHAR(255) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_general_ci`, zbsnotify_parameters TEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsnotify_reference_id INT NOT NULL, zbsnotify_created_at INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_object_links (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsol_objtype_from INT NOT NULL, zbsol_objtype_to INT NOT NULL, zbsol_objid_from INT NOT NULL, zbsol_objid_to INT NOT NULL, INDEX zbsol_objid_from (zbsol_objid_from), INDEX zbsol_objid_to (zbsol_objid_to), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_quotes (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsq_id_override VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsq_title VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsq_currency VARCHAR(4) CHARACTER SET utf8 DEFAULT \'-1\' NOT NULL COLLATE `utf8_general_ci`, zbsq_value NUMERIC(18, 2) DEFAULT \'0.00\', zbsq_date INT NOT NULL, zbsq_template VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsq_content LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsq_notes LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsq_hash VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsq_send_attachments TINYINT(1) DEFAULT -1 NOT NULL, zbsq_lastviewed INT DEFAULT -1, zbsq_viewed_count INT DEFAULT 0, zbsq_accepted INT DEFAULT -1, zbsq_acceptedsigned VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsq_acceptedip VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsq_created INT NOT NULL, zbsq_lastupdated INT NOT NULL, INDEX hash (zbsq_hash), INDEX created (zbsq_created), INDEX title (zbsq_title), INDEX accepted (zbsq_accepted), INDEX dateint (zbsq_date), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_quotes_templates (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsqt_title VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsqt_value NUMERIC(18, 2) DEFAULT \'0.00\', zbsqt_date_str VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsqt_date INT DEFAULT NULL, zbsqt_content LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsqt_notes LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsqt_currency VARCHAR(4) CHARACTER SET utf8 DEFAULT \'-1\' NOT NULL COLLATE `utf8_general_ci`, zbsqt_created INT NOT NULL, zbsqt_lastupdated INT NOT NULL, INDEX title (zbsqt_title), INDEX created (zbsqt_created), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_security_log (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbssl_reqtype VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbssl_ip VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbssl_reqhash VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbssl_reqid INT DEFAULT NULL, zbssl_loggedin_id INT DEFAULT NULL, zbssl_reqstatus INT DEFAULT NULL, zbssl_reqtime INT DEFAULT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_segments (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsseg_name VARCHAR(120) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsseg_slug VARCHAR(45) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsseg_matchtype VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsseg_created INT NOT NULL, zbsseg_lastupdated INT NOT NULL, zbsseg_compilecount INT DEFAULT 0, zbsseg_lastcompiled INT NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_segments_conditions (ID INT AUTO_INCREMENT NOT NULL, zbscondition_segmentid INT NOT NULL, zbscondition_type VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbscondition_op VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbscondition_val VARCHAR(250) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbscondition_val_secondary VARCHAR(250) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_settings (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsset_key VARCHAR(100) CHARACTER SET utf8 DEFAULT \'-1\' NOT NULL COLLATE `utf8_general_ci`, zbsset_val LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsset_created INT NOT NULL, zbsset_lastupdated INT NOT NULL, INDEX zbsset_key (zbsset_key), INDEX zbs_owner (zbs_owner), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_sys_cronmanagerlogs (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, job VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, jobstatus INT DEFAULT NULL, jobstarted INT NOT NULL, jobfinished INT NOT NULL, jobnotes LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_sys_email (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsmail_active INT NOT NULL, zbsmail_id INT NOT NULL, zbsmail_deliverymethod VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsmail_fromname VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_fromaddress VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_replyto VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_ccto VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_bccto VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_subject VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_body LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_created INT NOT NULL, zbsmail_lastupdated INT NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_sys_email_hist (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsmail_type INT NOT NULL, zbsmail_sender_thread INT NOT NULL, zbsmail_sender_email VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsmail_sender_wpid INT NOT NULL, zbsmail_sender_mailbox_id INT NOT NULL, zbsmail_sender_mailbox_name VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_receiver_email VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbsmail_sent INT NOT NULL, zbsmail_target_objid INT NOT NULL, zbsmail_assoc_objid INT NOT NULL, zbsmail_subject VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_content LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_hash VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_status VARCHAR(120) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_sender_maildelivery_key VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsmail_starred INT DEFAULT NULL, zbsmail_opened INT NOT NULL, zbsmail_clicked INT NOT NULL, zbsmail_firstopened INT NOT NULL, zbsmail_lastopened INT NOT NULL, zbsmail_lastclicked INT NOT NULL, zbsmail_created INT NOT NULL, INDEX zbsmail_sender_mailbox_id (zbsmail_sender_mailbox_id), INDEX zbsmail_sender_wpid (zbsmail_sender_wpid), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_tags (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbstag_objtype INT NOT NULL, zbstag_name VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbstag_slug VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbstag_created INT NOT NULL, zbstag_lastupdated INT NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_tags_links (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbstl_objtype INT NOT NULL, zbstl_objid INT NOT NULL, zbstl_tagid INT NOT NULL, INDEX zbstl_objid (zbstl_objid), INDEX zbstl_tagid (zbstl_tagid), INDEX zbstl_tagid+zbstl_objtype (zbstl_tagid, zbstl_objtype), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_tax_table (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbsc_tax_name VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbsc_rate NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbsc_created INT NOT NULL, zbsc_lastupdated INT NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_temphash (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbstemphash_status INT DEFAULT -1, zbstemphash_objtype VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbstemphash_objid INT DEFAULT NULL, zbstemphash_objhash VARCHAR(256) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbstemphash_created INT NOT NULL, zbstemphash_lastupdated INT NOT NULL, zbstemphash_expiry INT NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_tracking (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbst_contactid INT NOT NULL, zbst_action VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_action_detail LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_referrer VARCHAR(300) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_utm_source VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_utm_medium VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_utm_name VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_utm_term VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_utm_content VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_created INT NOT NULL, zbst_lastupdated INT NOT NULL, PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_transactions (ID INT AUTO_INCREMENT NOT NULL, zbs_site INT DEFAULT NULL, zbs_team INT DEFAULT NULL, zbs_owner INT NOT NULL, zbst_status VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_type VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbst_ref VARCHAR(120) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, zbst_origin VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbst_parent INT DEFAULT NULL, zbst_hash VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbst_title VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbst_desc VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbst_date INT DEFAULT NULL, zbst_customer_ip VARCHAR(45) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbst_currency VARCHAR(4) CHARACTER SET utf8 DEFAULT \'-1\' NOT NULL COLLATE `utf8_general_ci`, zbst_net NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbst_fee NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbst_discount NUMERIC(18, 2) DEFAULT \'0.00\', zbst_shipping NUMERIC(18, 2) DEFAULT \'0.00\', zbst_shipping_taxes VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbst_shipping_tax NUMERIC(18, 2) DEFAULT \'0.00\', zbst_taxes VARCHAR(40) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, zbst_tax NUMERIC(18, 2) DEFAULT \'0.00\', zbst_total NUMERIC(18, 2) DEFAULT \'0.00\' NOT NULL, zbst_date_paid INT DEFAULT NULL, zbst_date_completed INT DEFAULT NULL, zbst_created INT NOT NULL, zbst_lastupdated INT NOT NULL, INDEX created (zbst_created), INDEX hash (zbst_hash), INDEX transtype (zbst_type), INDEX date (zbst_date), INDEX transorigin (zbst_origin), INDEX status (zbst_status), INDEX title (zbst_title), INDEX parent (zbst_parent), INDEX ref (zbst_ref), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_bmszbs_workflows (id INT AUTO_INCREMENT NOT NULL, zbs_site INT NOT NULL, zbs_team INT NOT NULL, zbs_owner INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, description VARCHAR(600) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, category VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, triggers LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, initial_step VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, steps LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, active TINYINT(1) DEFAULT 0 NOT NULL, version INT DEFAULT 1 NOT NULL, created_at INT DEFAULT NULL, updated_at INT DEFAULT NULL, INDEX active (active), INDEX category (category), INDEX created_at (created_at), INDEX name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE user DROP status, CHANGE roles roles LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE interesrt_course interesrt_course LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
    }
}
